# font
[font]
size = 10.0
normal = { family = "Jetbrains Mono Nerd Font", style = "Regular" }

[cursor]
style = "Block"
vi_mode_style = "Block"

[general]
# theme
import = [
    "~/.config/alacritty/themes/themes/terafox.toml"
]
