# font
[font]
size = 9.0
normal = { family = "monospace", style = "Regular" }

[cursor]
style = "Block"
vi_mode_style = "Block"

[window]
opacity = 1.0

[general]
# theme
import = [
    "~/.config/alacritty/themes/themes/terafox.toml"
]
