# theme
import = [
    "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]

# font
[font]
size = 11.0
normal = { family = "Jetbrains Mono Nerd Font Mono", style = "Regular" }

[cursor]
style = "Block"
vi_mode_style = "Block"
