# ~/.config/foot/themes/ef-dream.ini

[colors-dark]
alpha=1.0

foreground=efd5c5
background=232025

selection-foreground=efd5c5
selection-background=544a50


# ANSI 0-7
regular0=232025
regular1=ff6f6f
regular2=51b04f
regular3=c0b24f
regular4=57b0ff
regular5=ffaacf
regular6=6fb3c0
regular7=efd5c5

# ANSI 8-15
bright0=8f8886
bright1=ff7a5f
bright2=7fce5f
bright3=d09950
bright4=80aadf
bright5=d0b0ff
bright6=8fcfd0
bright7=fedeff

urls=deb07a
