# ~/.config/foot/themes/ef-reverie.ini

[colors-dark]
alpha=1.0

foreground=4f204f
background=f3eddf

selection-foreground=4f204f
selection-background=e0d0ba

# Regular ANSI colors
regular0=f3eddf
regular1=ba2d2f
regular2=007a0a
regular3=87591f
regular4=375cc6
regular5=9f4e74
regular6=3060af
regular7=4f204f

# Bright ANSI colors
bright0=6f6877
bright1=b21f00
bright2=5a7400
bright3=a05900
bright4=5059c0
bright5=7755b4
bright6=0b6e8a
bright7=55447f

urls=906045
