colorscheme zenburn

map global user l ':enter-user-mode lsp<ret>' -docstring 'LSP mode'

map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'

map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
map global object t '<a-semicolon>lsp-object Class Interface Struct<ret>' -docstring 'LSP class interface or struct'
map global object d '<a-semicolon>lsp-diagnostic-object --include-warnings<ret>' -docstring 'LSP errors and warnings'
map global object D '<a-semicolon>lsp-diagnostic-object<ret>' -docstring 'LSP errors'

set-option global tabstop 4
set-option global indentwidth 4
set-option global scrolloff 1,3
set-option -add global ui_options terminal_assistant=none
add-highlighter global/ number-lines -relative
# add-highlighter global/ regex \h+$ 0:Error


source "%val{config}/smarttab.kak"
hook global BufOpenFile .* expandtab
hook global BufNewFile  .* expandtab

hook global WinSetOption filetype=haskell %{
    set-option window tabstop 2
    set-option window indentwidth 2
}

eval %sh{kak-lsp}
lsp-enable

