return {
    {
        'nvim-treesitter/nvim-treesitter',
        enabled = true,
        lazy = false,
        branch = "main",
        build = ':TSUpdate',
        opts = {},
        config = function()
            local ensure_installed = {
                "ada",
                "agda",
                "asm",
                "bash",
                "c",
                "c_sharp",
                "clojure",
                "cmake",
                "cpp",
                "css",
                "diff",
                "git_config",
                "glsl",
                "go",
                "haskell",
                "html",
                "java",
                "javadoc",
                "javascript",
                "json",
                "jsonc",
                "kotlin",
                -- "latex",
                "lua",
                "luadoc",
                "luap",
                "make",
                "markdown",
                "markdown_inline",
                "ocaml",
                "perl",
                "php",
                "python",
                "query",
                "r",
                "regex",
                "rust",
                "toml",
                "typescript",
                "vim",
                "vimdoc",
                "xml",
                "yaml",
                "zig",
            }
            require 'nvim-treesitter'.install(ensure_installed)

            vim.api.nvim_create_autocmd('FileType', {
                pattern = {
                    'ada',
                    'asm',
                    'bash',
                    'c',
                    'cpp',
                    'cmake',
                    'c_sharp',
                    'css',
                    'clojure',
                    'go',
                    'haskell',
                    'html',
                    'java',
                    'javascript',
                    'json',
                    'kotlin',
                    'lua',
                    'ocaml',
                    'perl',
                    'php',
                    'python',
                    'r',
                    'rust',
                    'toml',
                    'typescript',
                    'vim',
                    'xml',
                    'yaml',
                    'zig',
                },
                callback = function() vim.treesitter.start() end,
            })
        end
    }
}
